const source = {
    "type": "source1",
    "fields": {
      "apiKey": {
        "type": "input",
        "label": "API key",
        "regexErrorMessage": "Invalid api key",
        "placeholder": "First Value",
        "regex": "[a-z0-9]",
        "required": true,
        "value": "",
      },
      "type": {
        "type": "input",
        "label": "API key",
        "regexErrorMessage": "Invalid api key",
        "placeholder": "Second Value",
        "regex": "[a-z0-9]",
        "required": true,
        "value": "",
      },
      "apiKey3": {
        "type": "input",
        "label": "API key",
        "regexErrorMessage": "Invalid api key",
        "placeholder": "First Value",
        "regex": "[a-z0-9]",
        "required": true,
        "value": "",
      },
      "apiKey4": {
        "type": "input",
        "label": "API key",
        "regexErrorMessage": "Invalid api key",
        "placeholder": "Second Value",
        "regex": "[a-z0-9]",
        "required": true,
        "value": "",
      },
      "useHTTP": {
        "type": "checkbox",
        "required": false,
        "label": "Enable HTTP",
        "value": "",
      },
      "udseHTTP": {
        "type": "checkbox",
        "required": false,
        "label": "Enable HTTP",
        "value": "",
      },
      "category": {
        "type": "singleSelect",
        "label": "Select category",
        "required": true,
        "value": "",
        "options": [
          { "label": "Android", "value": "android" },
          { "label": "IOS", "value": "ios" },
        ],
      },
      "category1": {
        "type": "singleSelect",
        "label": "Select category",
        "required": true,
        "value": "",
        "options": [
          { "label": "Android", "value": "android" },
          { "label": "IOS", "value": "ios" },
          { "label": "lg", "value": "lg" },
          { "label": "sony", "value": "sony" },
        ],
      },
      "radio": {
        "type": "radio",
        "label": "Select category",
        "required": true,
        "value": "",
        "options": [
          { "label": "Android", "value": "android" },
          { "label": "IOS", "value": "ios" },
          { "label": "lg", "value": "lg" },
          { "label": "sony", "value": "sony" },
        ],
      },
      "radio1": {
        "type": "radio",
        "label": "Select category",
        "required": true,
        "value": "",
        "options": [
          { "label": "Android", "value": "android" },
          { "label": "IOS", "value": "ios" },
          { "label": "lg", "value": "lg" },
          { "label": "sony", "value": "sony" },
        ],
      },
    },
  };